# Site settings
title: Alex's Blog
email: me@alexrulkens.com
description: > # this means to ignore newlines until "baseurl:"
  Alex's adventures in the crazy world of UX design and front-end development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rulkens.github.io" # the base hostname & protocol for your site
twitter_username: thereallex
github_username:  rulkens

# Build settings
markdown: kramdown
